// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';


function Make() {
  return /* module */[];
}

var StatefulRP = /* module */[/* Make */Make];

var Stateful = [(function () {
      var S = /* module */[];
      Make(S);
      /* module */[/* S */S];
      return [];
    })];

exports.StatefulRP = StatefulRP;
exports.Stateful = Stateful;
/* No side effect */
