// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function s_(prim) {
  return prim;
}

function a_(prim) {
  return prim;
}

var l_ = Belt_List.toArray;

exports.s_ = s_;
exports.a_ = a_;
exports.l_ = l_;
/* No side effect */
